### ISSUE TITLE
No favicon kills Node

### ISSUE THREAD

**Issue by poshaughnessy** [Rich-Harris/svelte-ssr-bundle#1]
Hi Rich! With Node v7 on Ubuntu, `npm start` fires up the server but when I request the page in Chrome, Node crashes with:

```Error: ENOENT: no such file or directory, open '/home/[bla bla path removed]/favicon.ico'```

(I can avoid the error for now by adding a favicon of course, but...) looks like it's down to the error handling around `fs.createReadStream` in `server/index.js` (line 28). Changing it to this appears to fix it for me:

```
const rs = fs.createReadStream( filename );
rs.on( 'error', err => {
    res.statusCode = 404;
    res.end( 'not found' );
});
rs.pipe( res );
```

(Not very familiar with this, but I could submit this as a PR if you like...)

**Comment by Rich-Harris** [comment]
Ah, I didn't realise that `createReadStream` errors asynchronously if the file doesn't exist. Interesting! Thanks – no need to mess around with a PR, I just fixed it via the web interface

**Comment by poshaughnessy** [comment]
Works for me - thanks!
